version: '3.8'

services:
  postmath:
    build:
      context: .
      dockerfile: apps/postmath/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  unitflip:
    build:
      context: .
      dockerfile: apps/unitflip/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  budgetcron:
    build:
      context: .
      dockerfile: apps/budgetcron/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ai4kids:
    build:
      context: .
      dockerfile: apps/ai4kids/Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  multiai:
    build:
      context: .
      dockerfile: apps/multiai/Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
