# =============================================================================
# CONFIGURATION NETLIFY - MATH4CHILD (CORRIGÉE)
# =============================================================================

[build]
  base = "apps/math4child"
  publish = "apps/math4child/out"
  command = "cd apps/math4child && npm install --legacy-peer-deps && npm run build && npm run export"

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_ENV = "production"
  CAPACITOR_BUILD = "false"

# Variables d'environnement production
[context.production.environment]
  NODE_ENV = "production"
  CAPACITOR_BUILD = "false"
  NEXT_PUBLIC_SITE_URL = "https://prismatic-sherbet-986159.netlify.app"

# Redirection SPA pour Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour assets statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
