[build]
  command = "cd apps/math4child && npm ci --legacy-peer-deps && npm run build"
  publish = "apps/math4child/out"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.production]
  command = "cd apps/math4child && npm ci --legacy-peer-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
