# =============================================================================
# CONFIGURATION NETLIFY - MATH4CHILD
# =============================================================================

[build]
  base = "apps/math4child"
  publish = "out"
  command = "npm install --legacy-peer-deps --force && npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_ENV = "production"
  DEFAULT_LANGUAGE = "fr"
  NETLIFY_SKIP_EDGE_FUNCTIONS_BUNDLING = "true"

# Variables d'environnement production
[context.production.environment]
  NODE_ENV = "production"
  DEFAULT_LANGUAGE = "fr"
  NEXT_PUBLIC_SITE_URL = "https://math4child.netlify.app"
  
  # Clés de test pour providers de paiement
  PADDLE_CLIENT_TOKEN = "test_paddle_token"
  LEMONSQUEEZY_API_KEY = "test_ls_key"
  REVENUECAT_API_KEY = "test_rc_key"
  NEXT_PUBLIC_REVENUECAT_PUBLIC_KEY = "pk_test_rc_public"
  
  # Stripe fallback
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_stripe_key"
  STRIPE_SECRET_KEY = "sk_test_stripe_key"

# Variables d'environnement preview
[context.deploy-preview.environment]
  NODE_ENV = "development"
  DEFAULT_LANGUAGE = "fr"
  NEXT_PUBLIC_SITE_URL = "$DEPLOY_PRIME_URL"

# Variables d'environnement branches
[context.branch-deploy.environment]
  NODE_ENV = "development"
  DEFAULT_LANGUAGE = "fr"
  NEXT_PUBLIC_SITE_URL = "$DEPLOY_PRIME_URL"

# Redirection SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour assets statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
