[build]
  base = "apps/math4child"
  publish = "out"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  DEFAULT_LANGUAGE = "fr"

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://www.math4child.com"
  DEFAULT_LANGUAGE = "fr"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_SITE_URL = "$DEPLOY_PRIME_URL"

[[redirects]]
  from = "https://math4child.com/*"
  to = "https://www.math4child.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://prismatic-sherbet-986159.netlify.app/*"
  to = "https://www.math4child.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
