# =============================================================================
# NETLIFY.TOML MINIMAL ET FONCTIONNEL - MATH4CHILD
# =============================================================================

[build]
  base = "apps/math4child"
  publish = "apps/math4child/out"
  command = "npm install --legacy-peer-deps --force && npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_ENV = "production"
  DEFAULT_LANGUAGE = "fr"
  NETLIFY_SKIP_EDGE_FUNCTIONS_BUNDLING = "true"

# Variables d'environnement production
[context.production.environment]
  NODE_ENV = "production"
  DEFAULT_LANGUAGE = "fr"
  NEXT_PUBLIC_SITE_URL = "https://math4child.netlify.app"

# Variables d'environnement preview
[context.deploy-preview.environment]
  NODE_ENV = "development"
  DEFAULT_LANGUAGE = "fr"
  NEXT_PUBLIC_SITE_URL = "$DEPLOY_PRIME_URL"

# Variables d'environnement branches
[context.branch-deploy.environment]
  NODE_ENV = "development"
  DEFAULT_LANGUAGE = "fr"
  NEXT_PUBLIC_SITE_URL = "$DEPLOY_PRIME_URL"

# Redirection SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité essentiels
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour Next.js
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"