# =============================================================================
# NETLIFY.TOML CORRIGÉ POUR MATH4CHILD
# =============================================================================

[build]
  base = "apps/math4child"
  publish = "apps/math4child/out"
  # CORRECTION PRINCIPALE: Installation des dépendances avant build
  command = "npm install --legacy-peer-deps --force && npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.8.1"
  NODE_ENV = "production"
  DEFAULT_LANGUAGE = "fr"
  NETLIFY_SKIP_EDGE_FUNCTIONS_BUNDLING = "true"
  # Ajout pour compatibilité des dépendances
  NPM_FLAGS = "--legacy-peer-deps"

# Variables d'environnement pour tous les contextes
[context.production.environment]
  NODE_ENV = "production"
  DEFAULT_LANGUAGE = "fr"
  NEXT_PUBLIC_SITE_URL = "https://math4child.netlify.app"
  
  # Clés de test pour les providers de paiement
  PADDLE_CLIENT_TOKEN = "test_paddle_token"
  LEMONSQUEEZY_API_KEY = "test_ls_key"
  REVENUECAT_API_KEY = "test_rc_key"
  NEXT_PUBLIC_REVENUECAT_PUBLIC_KEY = "pk_test_rc_public"
  
  # Stripe fallback
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_stripe_key"
  STRIPE_SECRET_KEY = "sk_test_stripe_key"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  DEFAULT_LANGUAGE = "fr"
  NEXT_PUBLIC_SITE_URL = "$DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  DEFAULT_LANGUAGE = "fr"
  NEXT_PUBLIC_SITE_URL = "$DEPLOY_PRIME_URL"

# Redirection SPA pour Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirections API (si webhooks nécessaires)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  conditions = {Role = ["admin"]}

# Headers de sécurité (adaptés du second fichier)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers pour les manifests
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

# Cache optimisé pour Next.js
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Headers pour les images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Configuration pour optimiser les builds
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Fonction de timeout étendue pour build complexe
[functions]
  timeout = 60