[build]
  base = "apps/math4child"
  publish = "apps/math4child/out"
  command = "cd apps/math4child && npm install --no-audit && ./build-safe.sh"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.8.0"
  SKIP_LINT = "true"
  SKIP_TYPE_CHECK = "true"

[context.production]
  command = "cd apps/math4child && npm install --no-audit && ./build-safe.sh"

[context."feature/math4child"]
  command = "cd apps/math4child && npm install --no-audit && ./build-safe.sh"

[context.branch-deploy]
  command = "cd apps/math4child && npm install --no-audit && ./build-safe.sh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
