'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

interface LanguageContextType {
  currentLanguage: string
  setLanguage: (lang: string) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// DICTIONNAIRE COMPLET AVEC TOUTES LES LANGUES EUROPÉENNES
const translations: Record<string, Record<string, string>> = {
  // ============================================================================
  // LANGUES PRINCIPALES DÉJÀ EXISTANTES
  // ============================================================================
  fr: { 
    'app_name': 'Mathématiques pour Enfants', 'app_name_short': 'Math4Enfants', 'website': 'www.math4child.com', 'world_leader': 'Leader mondial', 'families_trust': '100k+ familles', 'app_educative': 'App éducative #1 en France', 'main_title': 'Mathématiques pour Enfants', 'main_subtitle': "L'app éducative #1 pour apprendre les mathématiques en famille", 'join_families': 'Rejoignez plus de 100.000 familles qui apprennent déjà !', 'start_free': 'Commencer gratuitement', 'trial_14d': '14j gratuit', 'compare_prices': 'Comparer les prix', 'plan_free': 'Gratuit', 'plan_trial_14': 'Essai 14j', 'plan_trial_7': 'Essai 7j', 'plan_family': 'Plan Famille', 'community_support': 'Support communautaire', 'offline_limited': 'Mode hors-ligne limité', 'unlimited_questions': 'Questions illimitées', 'complete_levels': '5 niveaux complets', 'child_profiles_5': '5 profils enfants', 'child_profiles_2': '2 profils', 'languages_30_complete': '30+ langues complètes', 'languages_30': '30+ langues', 'offline_total': 'Mode hors-ligne total', 'offline_mode': 'Mode hors-ligne', 'student_profiles_30': '30 profils élèves', 'teacher_dashboard': 'Tableau de bord enseignant', 'homework_assignment': 'Assignation de devoirs', 'detailed_reports': 'Rapports de classe détaillés', 'family_plan_all': 'Tout du plan Famille', 'free_trial_14': 'Essai 14j gratuit', 'free_trial_7': 'Essai 7j gratuit', 'free_trial_30': 'Essai 30j gratuit', 'start_free_btn': 'Commencer gratuitement', 'select_language': 'Sélectionner une langue', 'new_advanced_dropdown': 'NOUVEAU DROPDOWN AVANCÉ', 'ultra_intelligent_search': 'RECHERCHE ULTRA-INTELLIGENTE', 'languages_found': 'langues trouvées', 'language_found': 'langue trouvée', 'for_search': 'pour', 'new_version_2024': 'NOUVELLE VERSION 2024', 'current': 'ACTUELLE', 'no_language_found': 'Aucune langue trouvée', 'try_search': 'Essayez: "français", "english", "中文", "العربية"'
  },
  
  en: { 
    'app_name': 'Math for Children', 'app_name_short': 'Math4Children', 'website': 'www.math4child.com', 'world_leader': 'World Leader', 'families_trust': '100k+ families', 'app_educative': '#1 educational app in France', 'main_title': 'Math for Children', 'main_subtitle': 'The #1 educational app to learn mathematics as a family', 'join_families': 'Join over 100,000 families already learning!', 'start_free': 'Start for free', 'trial_14d': '14d free', 'compare_prices': 'Compare prices', 'plan_free': 'Free', 'plan_trial_14': '14-day Trial', 'plan_trial_7': '7-day Trial', 'plan_family': 'Family Plan', 'community_support': 'Community support', 'offline_limited': 'Limited offline mode', 'unlimited_questions': 'Unlimited questions', 'complete_levels': '5 complete levels', 'child_profiles_5': '5 child profiles', 'child_profiles_2': '2 profiles', 'languages_30_complete': '30+ complete languages', 'languages_30': '30+ languages', 'offline_total': 'Full offline mode', 'offline_mode': 'Offline mode', 'student_profiles_30': '30 student profiles', 'teacher_dashboard': 'Teacher dashboard', 'homework_assignment': 'Homework assignment', 'detailed_reports': 'Detailed class reports', 'family_plan_all': 'Everything in Family plan', 'free_trial_14': '14-day free trial', 'free_trial_7': '7-day free trial', 'free_trial_30': '30-day free trial', 'start_free_btn': 'Start for free', 'select_language': 'Select a language', 'new_advanced_dropdown': 'NEW ADVANCED DROPDOWN', 'ultra_intelligent_search': 'ULTRA-INTELLIGENT SEARCH', 'languages_found': 'languages found', 'language_found': 'language found', 'for_search': 'for', 'new_version_2024': 'NEW VERSION 2024', 'current': 'CURRENT', 'no_language_found': 'No language found', 'try_search': 'Try: "français", "english", "中文", "العربية"'
  },
  
  es: { 
    'app_name': 'Matemáticas para Niños', 'app_name_short': 'Mate4Niños', 'website': 'www.math4child.com', 'world_leader': 'Líder Mundial', 'families_trust': '100k+ familias', 'app_educative': 'App educativa #1 en Francia', 'main_title': 'Matemáticas para Niños', 'main_subtitle': 'La app educativa #1 para aprender matemáticas en familia', 'join_families': '¡Únete a más de 100,000 familias que ya están aprendiendo!', 'start_free': 'Comenzar gratis', 'trial_14d': '14d gratis', 'compare_prices': 'Comparar precios', 'plan_free': 'Gratis', 'plan_trial_14': 'Prueba 14d', 'plan_trial_7': 'Prueba 7d', 'plan_family': 'Plan Familiar', 'community_support': 'Soporte comunitario', 'offline_limited': 'Modo sin conexión limitado', 'unlimited_questions': 'Preguntas ilimitadas', 'complete_levels': '5 niveles completos', 'child_profiles_5': '5 perfiles de niños', 'child_profiles_2': '2 perfiles', 'languages_30_complete': '30+ idiomas completos', 'languages_30': '30+ idiomas', 'offline_total': 'Modo sin conexión total', 'offline_mode': 'Modo sin conexión', 'student_profiles_30': '30 perfiles de estudiantes', 'teacher_dashboard': 'Panel de profesor', 'homework_assignment': 'Asignación de tareas', 'detailed_reports': 'Informes detallados de clase', 'family_plan_all': 'Todo del plan Familiar', 'free_trial_14': 'Prueba gratis 14d', 'free_trial_7': 'Prueba gratis 7d', 'free_trial_30': 'Prueba gratis 30d', 'start_free_btn': 'Comenzar gratis', 'select_language': 'Seleccionar idioma', 'new_advanced_dropdown': 'NUEVO DROPDOWN AVANZADO', 'ultra_intelligent_search': 'BÚSQUEDA ULTRA-INTELIGENTE', 'languages_found': 'idiomas encontrados', 'language_found': 'idioma encontrado', 'for_search': 'para', 'new_version_2024': 'NUEVA VERSIÓN 2024', 'current': 'ACTUAL', 'no_language_found': 'Ningún idioma encontrado', 'try_search': 'Prueba: "français", "english", "中文", "العربية"'
  },
  
  de: { 
    'app_name': 'Mathematik für Kinder', 'app_name_short': 'Mathe4Kinder', 'website': 'www.math4child.com', 'world_leader': 'Weltmarktführer', 'families_trust': '100k+ Familien', 'app_educative': '#1 Bildungs-App in Frankreich', 'main_title': 'Mathematik für Kinder', 'main_subtitle': 'Die #1 Bildungs-App zum Mathematiklernen in der Familie', 'join_families': 'Schließe dich über 100.000 Familien an, die bereits lernen!', 'start_free': 'Kostenlos beginnen', 'trial_14d': '14T kostenlos', 'compare_prices': 'Preise vergleichen', 'plan_free': 'Kostenlos', 'plan_trial_14': '14-Tage Test', 'plan_trial_7': '7-Tage Test', 'plan_family': 'Familienplan', 'community_support': 'Community-Support', 'offline_limited': 'Begrenzter Offline-Modus', 'unlimited_questions': 'Unbegrenzte Fragen', 'complete_levels': '5 vollständige Level', 'child_profiles_5': '5 Kinderprofile', 'child_profiles_2': '2 Profile', 'languages_30_complete': '30+ vollständige Sprachen', 'languages_30': '30+ Sprachen', 'offline_total': 'Vollständiger Offline-Modus', 'offline_mode': 'Offline-Modus', 'student_profiles_30': '30 Schülerprofile', 'teacher_dashboard': 'Lehrer-Dashboard', 'homework_assignment': 'Hausaufgabenzuweisung', 'detailed_reports': 'Detaillierte Klassenberichte', 'family_plan_all': 'Alles vom Familienplan', 'free_trial_14': '14-Tage kostenlos testen', 'free_trial_7': '7-Tage kostenlos testen', 'free_trial_30': '30-Tage kostenlos testen', 'start_free_btn': 'Kostenlos beginnen', 'select_language': 'Sprache wählen', 'new_advanced_dropdown': 'NEUES ERWEITERTES DROPDOWN', 'ultra_intelligent_search': 'ULTRA-INTELLIGENTE SUCHE', 'languages_found': 'Sprachen gefunden', 'language_found': 'Sprache gefunden', 'for_search': 'für', 'new_version_2024': 'NEUE VERSION 2024', 'current': 'AKTUELL', 'no_language_found': 'Keine Sprache gefunden', 'try_search': 'Versuche: "français", "english", "中文", "العربية"'
  },
  
  it: { 
    'app_name': 'Matematica per Bambini', 'app_name_short': 'Mate4Bambini', 'website': 'www.math4child.com', 'world_leader': 'Leader Mondiale', 'families_trust': '100k+ famiglie', 'app_educative': 'App educativa #1 in Francia', 'main_title': 'Matematica per Bambini', 'main_subtitle': "L'app educativa #1 per imparare la matematica in famiglia", 'join_families': 'Unisciti a oltre 100.000 famiglie che stanno già imparando!', 'start_free': 'Inizia gratis', 'trial_14d': '14g gratis', 'compare_prices': 'Confronta prezzi', 'plan_free': 'Gratuito', 'plan_trial_14': 'Prova 14g', 'plan_trial_7': 'Prova 7g', 'plan_family': 'Piano Famiglia', 'community_support': 'Supporto della community', 'offline_limited': 'Modalità offline limitata', 'unlimited_questions': 'Domande illimitate', 'complete_levels': '5 livelli completi', 'child_profiles_5': '5 profili bambini', 'child_profiles_2': '2 profili', 'languages_30_complete': '30+ lingue complete', 'languages_30': '30+ lingue', 'offline_total': 'Modalità offline totale', 'offline_mode': 'Modalità offline', 'student_profiles_30': '30 profili studenti', 'teacher_dashboard': 'Dashboard insegnante', 'homework_assignment': 'Assegnazione compiti', 'detailed_reports': 'Report dettagliati della classe', 'family_plan_all': 'Tutto del piano Famiglia', 'free_trial_14': 'Prova gratuita 14g', 'free_trial_7': 'Prova gratuita 7g', 'free_trial_30': 'Prova gratuita 30g', 'start_free_btn': 'Inizia gratis', 'select_language': 'Seleziona lingua', 'new_advanced_dropdown': 'NUOVO DROPDOWN AVANZATO', 'ultra_intelligent_search': 'RICERCA ULTRA-INTELLIGENTE', 'languages_found': 'lingue trovate', 'language_found': 'lingua trovata', 'for_search': 'per', 'new_version_2024': 'NUOVA VERSIONE 2024', 'current': 'ATTUALE', 'no_language_found': 'Nessuna lingua trovata', 'try_search': 'Prova: "français", "english", "中文", "العربية"'
  },
  
  pt: { 
    'app_name': 'Matemática para Crianças', 'app_name_short': 'Mate4Crianças', 'website': 'www.math4child.com', 'world_leader': 'Líder Mundial', 'families_trust': '100k+ famílias', 'app_educative': 'App educativo #1 na França', 'main_title': 'Matemática para Crianças', 'main_subtitle': 'O app educativo #1 para aprender matemática em família', 'join_families': 'Junte-se a mais de 100.000 famílias que já estão aprendendo!', 'start_free': 'Começar grátis', 'trial_14d': '14d grátis', 'compare_prices': 'Comparar preços', 'plan_free': 'Gratuito', 'plan_trial_14': 'Teste 14d', 'plan_trial_7': 'Teste 7d', 'plan_family': 'Plano Família', 'community_support': 'Suporte da comunidade', 'offline_limited': 'Modo offline limitado', 'unlimited_questions': 'Perguntas ilimitadas', 'complete_levels': '5 níveis completos', 'child_profiles_5': '5 perfis de crianças', 'child_profiles_2': '2 perfis', 'languages_30_complete': '30+ idiomas completos', 'languages_30': '30+ idiomas', 'offline_total': 'Modo offline total', 'offline_mode': 'Modo offline', 'student_profiles_30': '30 perfis de estudantes', 'teacher_dashboard': 'Painel do professor', 'homework_assignment': 'Atribuição de lições', 'detailed_reports': 'Relatórios detalhados da turma', 'family_plan_all': 'Tudo do plano Família', 'free_trial_14': 'Teste grátis 14d', 'free_trial_7': 'Teste grátis 7d', 'free_trial_30': 'Teste grátis 30d', 'start_free_btn': 'Começar grátis', 'select_language': 'Selecionar idioma', 'new_advanced_dropdown': 'NOVO DROPDOWN AVANÇADO', 'ultra_intelligent_search': 'PESQUISA ULTRA-INTELIGENTE', 'languages_found': 'idiomas encontrados', 'language_found': 'idioma encontrado', 'for_search': 'para', 'new_version_2024': 'NOVA VERSÃO 2024', 'current': 'ATUAL', 'no_language_found': 'Nenhum idioma encontrado', 'try_search': 'Tente: "français", "english", "中文", "العربية"'
  },
  
  ru: { 
    'app_name': 'Математика для детей', 'app_name_short': 'Мат4Дети', 'website': 'www.math4child.com', 'world_leader': 'Мировой лидер', 'families_trust': '100k+семей', 'app_educative': '#1 образовательное приложение во Франции', 'main_title': 'Математика для детей', 'main_subtitle': '#1 образовательное приложение для изучения математики в семье', 'join_families': 'Присоединяйтесь к более чем 100,000 семей, которые уже учатся!', 'start_free': 'Начать бесплатно', 'trial_14d': '14д бесплатно', 'compare_prices': 'Сравнить цены', 'plan_free': 'Бесплатно', 'plan_trial_14': 'Пробная версия 14д', 'plan_trial_7': 'Пробная версия 7д', 'plan_family': 'Семейный план', 'community_support': 'Поддержка сообщества', 'offline_limited': 'Ограниченный офлайн режим', 'unlimited_questions': 'Неограниченные вопросы', 'complete_levels': '5 полных уровней', 'child_profiles_5': '5 детских профилей', 'child_profiles_2': '2 профиля', 'languages_30_complete': '30+ полных языков', 'languages_30': '30+ языков', 'offline_total': 'Полный офлайн режим', 'offline_mode': 'Офлайн режим', 'student_profiles_30': '30 профилей учеников', 'teacher_dashboard': 'Панель учителя', 'homework_assignment': 'Назначение домашних заданий', 'detailed_reports': 'Подробные отчеты класса', 'family_plan_all': 'Все из семейного плана', 'free_trial_14': 'Бесплатная пробная версия 14д', 'free_trial_7': 'Бесплатная пробная версия 7д', 'free_trial_30': 'Бесплатная пробная версия 30д', 'start_free_btn': 'Начать бесплатно', 'select_language': 'Выбрать язык', 'new_advanced_dropdown': 'НОВОЕ РАСШИРЕННОЕ МЕНЮ', 'ultra_intelligent_search': 'УЛЬТРА-УМНЫЙ ПОИСК', 'languages_found': 'языков найдено', 'language_found': 'язык найден', 'for_search': 'для', 'new_version_2024': 'НОВАЯ ВЕРСИЯ 2024', 'current': 'ТЕКУЩИЙ', 'no_language_found': 'Язык не найден', 'try_search': 'Попробуйте: "français", "english", "中文", "العربية"'
  },

  // ============================================================================
  // 🇳🇱 NÉERLANDAIS (Pays-Bas)
  // ============================================================================
  nl: {
    'app_name': 'Wiskunde voor Kinderen', 'app_name_short': 'Wisk4Kinderen', 'website': 'www.math4child.com', 'world_leader': 'Wereldleider', 'families_trust': '100k+ gezinnen', 'app_educative': '#1 educatieve app in Frankrijk', 'main_title': 'Wiskunde voor Kinderen', 'main_subtitle': 'De #1 educatieve app om wiskunde te leren met het gezin', 'join_families': 'Sluit je aan bij meer dan 100.000 gezinnen die al aan het leren zijn!', 'start_free': 'Gratis beginnen', 'trial_14d': '14d gratis', 'compare_prices': 'Prijzen vergelijken', 'plan_free': 'Gratis', 'plan_trial_14': '14-dagen proef', 'plan_trial_7': '7-dagen proef', 'plan_family': 'Gezinsplan', 'community_support': 'Community ondersteuning', 'offline_limited': 'Beperkte offline modus', 'unlimited_questions': 'Onbeperkte vragen', 'complete_levels': '5 volledige niveaus', 'child_profiles_5': '5 kindprofielen', 'child_profiles_2': '2 profielen', 'languages_30_complete': '30+ volledige talen', 'languages_30': '30+ talen', 'offline_total': 'Volledige offline modus', 'offline_mode': 'Offline modus', 'student_profiles_30': '30 leerlingprofielen', 'teacher_dashboard': 'Leraar dashboard', 'homework_assignment': 'Huiswerk toewijzing', 'detailed_reports': 'Gedetailleerde klasrapporten', 'family_plan_all': 'Alles van het gezinsplan', 'free_trial_14': '14-dagen gratis proef', 'free_trial_7': '7-dagen gratis proef', 'free_trial_30': '30-dagen gratis proef', 'start_free_btn': 'Gratis beginnen', 'select_language': 'Taal selecteren', 'new_advanced_dropdown': 'NIEUWE GEAVANCEERDE DROPDOWN', 'ultra_intelligent_search': 'ULTRA-INTELLIGENTE ZOEKEN', 'languages_found': 'talen gevonden', 'language_found': 'taal gevonden', 'for_search': 'voor', 'new_version_2024': 'NIEUWE VERSIE 2024', 'current': 'HUIDIGE', 'no_language_found': 'Geen taal gevonden', 'try_search': 'Probeer: "français", "english", "中文", "العربية"'
  },

  // ============================================================================
  // 🇵🇱 POLONAIS (Pologne)
  // ============================================================================
  pl: {
    'app_name': 'Matematyka dla Dzieci', 'app_name_short': 'Mat4Dzieci', 'website': 'www.math4child.com', 'world_leader': 'Światowy Lider', 'families_trust': '100k+ rodzin', 'app_educative': '#1 aplikacja edukacyjna we Francji', 'main_title': 'Matematyka dla Dzieci', 'main_subtitle': '#1 aplikacja edukacyjna do nauki matematyki w rodzinie', 'join_families': 'Dołącz do ponad 100 000 rodzin, które już się uczą!', 'start_free': 'Zacznij za darmo', 'trial_14d': '14 dni za darmo', 'compare_prices': 'Porównaj ceny', 'plan_free': 'Darmowy', 'plan_trial_14': 'Próba 14 dni', 'plan_trial_7': 'Próba 7 dni', 'plan_family': 'Plan Rodzinny', 'community_support': 'Wsparcie społeczności', 'offline_limited': 'Ograniczony tryb offline', 'unlimited_questions': 'Nieograniczone pytania', 'complete_levels': '5 kompletnych poziomów', 'child_profiles_5': '5 profili dzieci', 'child_profiles_2': '2 profile', 'languages_30_complete': '30+ kompletnych języków', 'languages_30': '30+ języków', 'offline_total': 'Pełny tryb offline', 'offline_mode': 'Tryb offline', 'student_profiles_30': '30 profili uczniów', 'teacher_dashboard': 'Panel nauczyciela', 'homework_assignment': 'Przydzielanie prac domowych', 'detailed_reports': 'Szczegółowe raporty klasowe', 'family_plan_all': 'Wszystko z planu rodzinnego', 'free_trial_14': '14-dniowa darmowa próba', 'free_trial_7': '7-dniowa darmowa próba', 'free_trial_30': '30-dniowa darmowa próba', 'start_free_btn': 'Zacznij za darmo', 'select_language': 'Wybierz język', 'new_advanced_dropdown': 'NOWA ZAAWANSOWANA LISTA', 'ultra_intelligent_search': 'ULTRA-INTELIGENTNE WYSZUKIWANIE', 'languages_found': 'języków znalezionych', 'language_found': 'język znaleziony', 'for_search': 'dla', 'new_version_2024': 'NOWA WERSJA 2024', 'current': 'BIEŻĄCY', 'no_language_found': 'Nie znaleziono języka', 'try_search': 'Spróbuj: "français", "english", "中文", "العربية"'
  },

  // Ajout des autres langues européennes (suédois, norvégien, danois, etc.)
  sv: {
    'app_name': 'Matematik för Barn', 'app_name_short': 'Mat4Barn', 'website': 'www.math4child.com', 'world_leader': 'Världsledare', 'families_trust': '100k+ familjer', 'app_educative': '#1 utbildningsapp i Frankrike', 'main_title': 'Matematik för Barn', 'main_subtitle': '#1 utbildningsapp för att lära matematik med familjen', 'join_families': 'Gå med i över 100 000 familjer som redan lär sig!', 'start_free': 'Börja gratis', 'trial_14d': '14d gratis', 'compare_prices': 'Jämför priser', 'plan_free': 'Gratis', 'plan_trial_14': '14-dagars provversion', 'plan_trial_7': '7-dagars provversion', 'plan_family': 'Familjeplan', 'community_support': 'Community-stöd', 'offline_limited': 'Begränsad offline-läge', 'unlimited_questions': 'Obegränsade frågor', 'complete_levels': '5 kompletta nivåer', 'child_profiles_5': '5 barnprofiler', 'child_profiles_2': '2 profiler', 'languages_30_complete': '30+ kompletta språk', 'languages_30': '30+ språk', 'offline_total': 'Fullständig offline-läge', 'offline_mode': 'Offline-läge', 'student_profiles_30': '30 elevprofiler', 'teacher_dashboard': 'Lärardashboard', 'homework_assignment': 'Läxförteckning', 'detailed_reports': 'Detaljerade klassrapporter', 'family_plan_all': 'Allt från familjeplanen', 'free_trial_14': '14-dagars gratis provversion', 'free_trial_7': '7-dagars gratis provversion', 'free_trial_30': '30-dagars gratis provversion', 'start_free_btn': 'Börja gratis', 'select_language': 'Välj språk', 'new_advanced_dropdown': 'NY AVANCERAD DROPDOWN', 'ultra_intelligent_search': 'ULTRA-INTELLIGENT SÖKNING', 'languages_found': 'språk hittade', 'language_found': 'språk hittat', 'for_search': 'för', 'new_version_2024': 'NY VERSION 2024', 'current': 'NUVARANDE', 'no_language_found': 'Inget språk hittades', 'try_search': 'Försök: "français", "english", "中文", "العربية"'
  },

  no: {
    'app_name': 'Matematikk for Barn', 'app_name_short': 'Mat4Barn', 'website': 'www.math4child.com', 'world_leader': 'Verdensleder', 'families_trust': '100k+ familier', 'app_educative': '#1 utdanningsapp i Frankrike', 'main_title': 'Matematikk for Barn', 'main_subtitle': '#1 utdanningsapp for å lære matematikk med familien', 'join_families': 'Bli med i over 100 000 familier som allerede lærer!', 'start_free': 'Start gratis', 'trial_14d': '14d gratis', 'compare_prices': 'Sammenlign priser', 'plan_free': 'Gratis', 'plan_trial_14': '14-dagers prøveperiode', 'plan_trial_7': '7-dagers prøveperiode', 'plan_family': 'Familieplan', 'community_support': 'Community-støtte', 'offline_limited': 'Begrenset offline-modus', 'unlimited_questions': 'Ubegrensede spørsmål', 'complete_levels': '5 komplette nivåer', 'child_profiles_5': '5 barneprofiler', 'child_profiles_2': '2 profiler', 'languages_30_complete': '30+ komplette språk', 'languages_30': '30+ språk', 'offline_total': 'Full offline-modus', 'offline_mode': 'Offline-modus', 'student_profiles_30': '30 elevprofiler', 'teacher_dashboard': 'Lærer dashboard', 'homework_assignment': 'Leksetildeling', 'detailed_reports': 'Detaljerte klasserapporter', 'family_plan_all': 'Alt fra familieplanen', 'free_trial_14': '14-dagers gratis prøveperiode', 'free_trial_7': '7-dagers gratis prøveperiode', 'free_trial_30': '30-dagers gratis prøveperiode', 'start_free_btn': 'Start gratis', 'select_language': 'Velg språk', 'new_advanced_dropdown': 'NY AVANSERT DROPDOWN', 'ultra_intelligent_search': 'ULTRA-INTELLIGENT SØKNING', 'languages_found': 'språk funnet', 'language_found': 'språk funnet', 'for_search': 'for', 'new_version_2024': 'NY VERSJON 2024', 'current': 'GJELDENDE', 'no_language_found': 'Ingen språk funnet', 'try_search': 'Prøv: "français", "english", "中文", "العربية"'
  },

  da: {
    'app_name': 'Matematik for Børn', 'app_name_short': 'Mat4Børn', 'website': 'www.math4child.com', 'world_leader': 'Verdensleder', 'families_trust': '100k+ familier', 'app_educative': '#1 uddannelsesapp i Frankrig', 'main_title': 'Matematik for Børn', 'main_subtitle': '#1 uddannelsesapp til at lære matematik med familien', 'join_families': 'Tilslut dig over 100.000 familier, der allerede lærer!', 'start_free': 'Start gratis', 'trial_14d': '14d gratis', 'compare_prices': 'Sammenlign priser', 'plan_free': 'Gratis', 'plan_trial_14': '14-dages prøveperiode', 'plan_trial_7': '7-dages prøveperiode', 'plan_family': 'Familieplan', 'community_support': 'Community-støtte', 'offline_limited': 'Begrænset offline-tilstand', 'unlimited_questions': 'Ubegrænsede spørgsmål', 'complete_levels': '5 komplette niveauer', 'child_profiles_5': '5 børneprofiler', 'child_profiles_2': '2 profiler', 'languages_30_complete': '30+ komplette sprog', 'languages_30': '30+ sprog', 'offline_total': 'Fuld offline-tilstand', 'offline_mode': 'Offline-tilstand', 'student_profiles_30': '30 elevprofiler', 'teacher_dashboard': 'Lærer dashboard', 'homework_assignment': 'Lektiefordeling', 'detailed_reports': 'Detaljerede klasserapporter', 'family_plan_all': 'Alt fra familieplanen', 'free_trial_14': '14-dages gratis prøveperiode', 'free_trial_7': '7-dages gratis prøveperiode', 'free_trial_30': '30-dages gratis prøveperiode', 'start_free_btn': 'Start gratis', 'select_language': 'Vælg sprog', 'new_advanced_dropdown': 'NY AVANCERET DROPDOWN', 'ultra_intelligent_search': 'ULTRA-INTELLIGENT SØGNING', 'languages_found': 'sprog fundet', 'language_found': 'sprog fundet', 'for_search': 'for', 'new_version_2024': 'NY VERSION 2024', 'current': 'NUVÆRENDE', 'no_language_found': 'Intet sprog fundet', 'try_search': 'Prøv: "français", "english", "中文", "العربية"'
  }
}

interface LanguageProviderProps {
  children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [currentLanguage, setCurrentLanguage] = useState('fr')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('math4child-language')
    if (savedLanguage && translations[savedLanguage]) {
      setCurrentLanguage(savedLanguage)
    } else {
      const browserLang = navigator.language.split('-')[0]
      if (translations[browserLang]) {
        setCurrentLanguage(browserLang)
      }
    }
  }, [])

  const setLanguage = (lang: string) => {
    setCurrentLanguage(lang)
    localStorage.setItem('math4child-language', lang)
    
    console.log('🌍 Langue changée vers:', lang)
    console.log('📱 Nouveau nom app:', translations[lang]?.['app_name'] || 'Math4Child')
    
    if ('vibrate' in navigator) {
      navigator.vibrate(50)
    }
  }

  const t = (key: string): string => {
    const translation = translations[currentLanguage]?.[key] || translations['en']?.[key] || key
    return translation
  }

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
