[build]
  publish = "dist"
  command = "npm run build"

# Redirections
[[redirects]]
  from = "https://spiffy-arithmetic-99342f.netlify.app/*"
  to = "https://math4child.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.math4child.com/*"
  to = "https://math4child.com/:splat"
  status = 301
  force = true

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data:; connect-src 'self'"

# Cache des assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache du service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[context.production.environment]
  NODE_ENV = "production"
