[build]
  base = "apps/math4child"
  publish = "apps/math4child/out"
  command = "npm install --no-audit --legacy-peer-deps && npm run build:safe"

[build.environment]
  NODE_VERSION = "20.9.0"
  NODE_ENV = "production"

[context."feature/math4child"]
  command = "npm install --no-audit && npm run build:safe"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
