[build]
  publish = "out"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Build Commands par environnement
[context.production]
  command = "npm ci --production=false && npm run build:netlify"
  environment = { NODE_ENV = "production", ENABLE_STRIPE_TESTS = "false" }

[context.deploy-preview]
  command = "npm ci --production=false && npm run build:preview"
  environment = { NODE_ENV = "development", ENABLE_STRIPE_TESTS = "true" }

[context.branch-deploy]
  command = "npm ci --production=false && npm run build:preview"

# Redirections SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirections Stripe Test (pour développement)
[[redirects]]
  from = "/stripe-test"
  to = "/stripe-test/index.html"
  status = 200

# Headers de sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Variables d'environnement de production
[context.production.environment]
  ENABLE_ANALYTICS = "true"
  STRIPE_TEST_MODE = "false"
  NEXT_PUBLIC_APP_ENV = "production"
  NEXT_PUBLIC_BASE_URL = "https://prismatic-sherbet-986159.netlify.app"

# Variables d'environnement de preview
[context.deploy-preview.environment]
  ENABLE_ANALYTICS = "false"
  STRIPE_TEST_MODE = "true"
  NEXT_PUBLIC_APP_ENV = "preview"
  DEBUG_MODE = "true"
