# Configuration Netlify Math4Child v4.2.0 - Multi-branche automatique

[build]
  base = "apps/math4child"
  command = "npm install --no-audit && npm run build:production"
  publish = "apps/math4child/out"

# Production (branche main)
[context.production]
  command = "npm install --no-audit && npm run build:production"
  environment = { NODE_ENV = "production", NEXT_PUBLIC_APP_ENV = "production" }

# Staging (branche feature/math4child)
[context."feature/math4child"]
  command = "npm install --no-audit && npm run build:staging"
  environment = { NODE_ENV = "staging", NEXT_PUBLIC_APP_ENV = "staging" }

# Development (toute branche feature/*)
[context."feature/*"]
  command = "npm install --no-audit && npm run build:development"
  environment = { NODE_ENV = "development", NEXT_PUBLIC_APP_ENV = "development" }

# Preview (pull requests)
[context.deploy-preview]
  command = "npm install --no-audit && npm run build:preview"
  environment = { NODE_ENV = "preview", NEXT_PUBLIC_APP_ENV = "preview" }

# Headers et redirections
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"
